/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#75777e",
        "tertiary-fixed-dim": "#bec6dd",
        "on-secondary-fixed": "#002019",
        "on-tertiary-fixed": "#131b2c",
        "surface-dim": "#d9dadb",
        "on-surface": "#191c1d",
        "inverse-surface": "#2e3132",
        "primary-container": "#15213c",
        "surface-container-high": "#e7e8e9",
        "surface-container-low": "#f3f4f5",
        "surface": "#f8f9fa",
        "secondary-container": "#67fad5",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#bac6e9",
        "on-primary-fixed": "#0e1b35",
        "on-primary-container": "#7d89a9",
        "on-secondary-container": "#00725d",
        "on-tertiary-fixed-variant": "#3f4759",
        "on-surface-variant": "#45464d",
        "primary-fixed": "#d9e2ff",
        "surface-bright": "#f8f9fa",
        "surface-tint": "#525e7c",
        "error": "#ba1a1a",
        "secondary-fixed": "#67fad5",
        "tertiary": "#040b1c",
        "secondary": { DEFAULT: 'var(--secondary)', foreground: 'var(--secondary-foreground)' },
        "outline-variant": "#c6c6ce",
        "background": 'var(--background)',
        "tertiary-fixed": "#dae2fa",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#3b4663",
        "inverse-on-surface": "#f0f1f2",
        "primary": { DEFAULT: 'var(--primary)', foreground: 'var(--primary-foreground)' },
        "surface-container": "#edeeef",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#81899e",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005141",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "tertiary-container": "#1a2233",
        "primary-fixed-dim": "#bac6e9",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#44ddba",
        "surface-container-highest": "#e1e3e4",
        foreground: 'var(--foreground)',
        muted: { DEFAULT: 'var(--muted)', foreground: 'var(--muted-foreground)' },
        accent: { DEFAULT: 'var(--accent)', foreground: 'var(--accent-foreground)' },
        card: { DEFAULT: 'var(--card)', foreground: 'var(--card-foreground)' },
        popover: { DEFAULT: 'var(--popover)', foreground: 'var(--popover-foreground)' },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        destructive: { DEFAULT: 'var(--destructive)', foreground: 'var(--destructive-foreground)' },
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif']
      },
    },
  },
  plugins: [],
}
