import type { Requirement, Phase, ContentCalendarItem } from './types-requirements'

type SeedRequirement = Omit<Requirement, 'id' | 'created_at' | 'updated_at'>
type SeedPhase = Omit<Phase, 'id'>
type SeedContentCalendar = Omit<ContentCalendarItem, 'id' | 'created_at' | 'updated_at'>

export const SEED_REQUIREMENTS: SeedRequirement[] = [
  {
    ref_id: 'R001',
    phase: 'Phase 0',
    domain: 'Identity',
    requirement: 'Fix provisioning flow — firm + owner + membership in single transaction',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: [],
    acceptance_criteria: 'New firm created; owner membership exists; JWT contains firm_id + role; no manual SQL',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Known blocker: Default Firm ghost record',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R002',
    phase: 'Phase 0',
    domain: 'Identity',
    requirement: 'Fix role model consistency across DB enum, JWT claims, and app permissions',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'No \'role not found\' errors; all 6 roles consistent across DB/JWT/app',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'OWNER role mismatch already observed',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R003',
    phase: 'Phase 0',
    domain: 'Identity',
    requirement: 'JWT custom claims include firm_id and role after login',
    type: 'Security',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'S' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'Decoded JWT shows correct firm_id and role for any authenticated user',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R010',
    phase: 'Phase 1',
    domain: 'Client',
    requirement: 'Contacts table — individuals linked to client accounts',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'contacts table with firm_id, client_id, type (primary/secondary), contact details, RLS',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Two-level compliance model requires this',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R011',
    phase: 'Phase 1',
    domain: 'Compliance',
    requirement: 'Risk assessment templates — sections, questions, field types, scoring weights',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'risk_assessment_templates + sections + questions tables; JSON schema per question; version support',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Tiered verification model: basic/standard/enhanced',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R012',
    phase: 'Phase 1',
    domain: 'Compliance',
    requirement: 'Risk assessments — company-level, linked to template version',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R011'],
    acceptance_criteria: 'risk_assessments table; auto-created from active template; immutable after approval',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: '6 sections, 21 questions based on Xama model',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R013',
    phase: 'Phase 1',
    domain: 'Compliance',
    requirement: 'Risk assessment responses — per question, immutable after approval',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R012'],
    acceptance_criteria: 'risk_assessment_responses table; immutable trigger; hash computed; snapshot of inputs',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R014',
    phase: 'Phase 1',
    domain: 'Compliance',
    requirement: 'AML checks — contact-level, per individual',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R010'],
    acceptance_criteria: 'aml_checks table; linked to contact_id; types: identity, PEP, sanctions',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Manual entry first, API integration later',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R015',
    phase: 'Phase 1',
    domain: 'Compliance',
    requirement: 'AML check results — immutable evidence records',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R014'],
    acceptance_criteria: 'aml_check_results table; immutable; hash; submitted_by/at; document type recorded',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R016',
    phase: 'Phase 1',
    domain: 'Compliance',
    requirement: 'Verification level templates — basic/standard/enhanced tiers',
    type: 'Database',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R011'],
    acceptance_criteria: 'verification_levels table; each level defines required checks and documents',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Determines what AML docs required per contact',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R017',
    phase: 'Phase 1',
    domain: 'Compliance',
    requirement: 'Monitoring config — per company and per contact',
    type: 'Database',
    priority: 'Medium' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'S' as Requirement['complexity'],
    dependencies: ['R010', 'R012'],
    acceptance_criteria: 'monitoring_config table; enabled/disabled toggle; frequency; last_checked',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Companies House + PEP/sanctions ongoing monitoring',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R018',
    phase: 'Phase 1',
    domain: 'Commercial',
    requirement: 'Seed B&L risk assessment template as platform default (21 questions)',
    type: 'Template',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R011'],
    acceptance_criteria: 'Platform default template seeded; 6 sections; all questions with correct field types and weights',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Competitive advantage — new firms get this free',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R019',
    phase: 'Phase 1',
    domain: 'Commercial',
    requirement: 'Seed B&L service catalogue as platform default (8 categories)',
    type: 'Template',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'All 8 service categories with pricing seeded as platform defaults',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'From services-pricing.md reference',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R020',
    phase: 'Phase 1',
    domain: 'Governance',
    requirement: 'RLS policies on all new tables (contacts, risk_assessments, aml_checks, etc.)',
    type: 'Security',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R010-R017'],
    acceptance_criteria: 'Every new table has firm_id + active RLS policy using JWT claim',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Test Group F dependency',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R021',
    phase: 'Phase 1',
    domain: 'Governance',
    requirement: 'Immutability triggers on risk_assessment_responses, aml_check_results',
    type: 'Security',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'S' as Requirement['complexity'],
    dependencies: ['R013', 'R015'],
    acceptance_criteria: 'UPDATE/DELETE blocked at DB level on both tables',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Test Group E dependency',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R030',
    phase: 'Phase 1.5',
    domain: 'Compliance',
    requirement: 'Risk scoring algorithm — highest-section-wins + weighted average tiebreaker',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R012', 'R013'],
    acceptance_criteria: 'IMMUTABLE DB function; weights: Identity 25%, Activities 20%, Geo 20%, Services 15%, Delivery 10%, EDD 10%',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Any section HIGH → overall HIGH; weighted avg for Medium vs Low',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R031',
    phase: 'Phase 1.5',
    domain: 'Compliance',
    requirement: 'Risk score runs — immutable, stores inputs snapshot and algorithm version',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R030'],
    acceptance_criteria: 'risk_score_runs record per scoring; inputs frozen; version tracked',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Reproducibility requirement',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R032',
    phase: 'Phase 1.5',
    domain: 'Compliance',
    requirement: 'Risk decisions — mutable with override governance',
    type: 'Database',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R031'],
    acceptance_criteria: 'Override requires OWNER/CO role + rationale + audit entry; one active decision per client',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R040',
    phase: 'Phase 2',
    domain: 'UI',
    requirement: 'Client detail page — status bar showing onboarding journey stages',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'Horizontal bar: Onboarding → Risk Assessment → AML → Engagement → Active → Review; clickable stages',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Green/amber/grey/red indicators',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R041',
    phase: 'Phase 2',
    domain: 'UI',
    requirement: 'Risk assessment accordion — sections expand/collapse with progress badges',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R012'],
    acceptance_criteria: 'Each section shows outstanding (red) + completed (blue) counts; overall progress bar',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Schema-driven from template, not hard-coded',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R042',
    phase: 'Phase 2',
    domain: 'UI',
    requirement: 'Contact detail page — AML tabs (Onboarding | AML Check | Monitoring | Documents)',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R010', 'R014'],
    acceptance_criteria: 'Each contact has independent AML status; tab navigation; monitoring toggle',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R043',
    phase: 'Phase 2',
    domain: 'UI',
    requirement: 'Sidebar navigation restructure',
    type: 'UI',
    priority: 'Medium' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R040'],
    acceptance_criteria: 'Clients → Accounts + Contacts; Compliance → Risk Assessments + AML; Templates section',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R044',
    phase: 'Phase 2',
    domain: 'UI',
    requirement: 'Contact management — add/edit/archive contacts per client',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R010'],
    acceptance_criteria: 'CRUD for contacts with type selection; link to AML check flow',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R050',
    phase: 'Phase 3',
    domain: 'Compliance',
    requirement: 'Risk assessment auto-created from template when client created',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R012', 'R040'],
    acceptance_criteria: 'Client creation triggers risk assessment from firm\'s active template',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R051',
    phase: 'Phase 3',
    domain: 'Compliance',
    requirement: 'Questionnaire rendered from template schema (not hard-coded)',
    type: 'UI',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R011', 'R041'],
    acceptance_criteria: 'Questions, field types, required flags all driven by template JSON schema',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Firms can customise templates',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R052',
    phase: 'Phase 3',
    domain: 'Compliance',
    requirement: 'Submit for review → Approve workflow (two-step)',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R051'],
    acceptance_criteria: 'Submit freezes responses as draft; Approve makes immutable; both audited',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Mirrors Xama pattern',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R053',
    phase: 'Phase 3',
    domain: 'Compliance',
    requirement: 'Risk level auto-calculated from responses using scoring algorithm',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R030', 'R051'],
    acceptance_criteria: 'Section scores combine per algorithm; overall level displayed; stored in risk_score_runs',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R060',
    phase: 'Phase 4',
    domain: 'Compliance',
    requirement: 'AML check creation per contact — manual entry form',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R014', 'R042'],
    acceptance_criteria: 'Form captures: AML result, PEP result, sanctions result, document type, verifier, date, notes',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Manual first; API integration designed for later',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R061',
    phase: 'Phase 4',
    domain: 'Compliance',
    requirement: 'Document upload and verification per contact',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R060'],
    acceptance_criteria: 'Upload ID documents; mark as verified/pending; link to aml_check_results',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Client portal will also use this',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R062',
    phase: 'Phase 4',
    domain: 'Compliance',
    requirement: 'Verification level enforcement — required docs per level',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R016', 'R060'],
    acceptance_criteria: 'Basic requires 1 ID; Standard requires 2 IDs + proof of address; Enhanced adds source of funds',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Template-driven, not hard-coded',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R070',
    phase: 'Phase 5',
    domain: 'Template',
    requirement: 'Template CRUD for firm admins — risk assessment templates',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R011'],
    acceptance_criteria: 'Create, edit, clone platform defaults; versioning (new version doesn\'t affect existing assessments)',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R071',
    phase: 'Phase 5',
    domain: 'Template',
    requirement: 'Engagement letter templates — configurable per firm',
    type: 'Template',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'Template includes sections, T&Cs, branding fields; firm can customise',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'AAT-aligned structure',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R072',
    phase: 'Phase 5',
    domain: 'Template',
    requirement: 'Job templates — recurring work types with default tasks',
    type: 'Template',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'Define job type, default tasks, recurrence, assigned role; drives task engine',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Deep workflow requirement',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R073',
    phase: 'Phase 5',
    domain: 'Template',
    requirement: 'Platform defaults read-only for firms; clone-and-customise flow',
    type: 'Workflow',
    priority: 'Medium' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R070'],
    acceptance_criteria: 'Firms see B&L defaults; can clone to own templates; cannot edit platform originals',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R080',
    phase: 'Phase 6',
    domain: 'Commercial',
    requirement: 'Service catalogue management per firm',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R019'],
    acceptance_criteria: 'CRUD for services; pricing; categories; firm-specific overrides of platform defaults',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R081',
    phase: 'Phase 6',
    domain: 'Commercial',
    requirement: 'Package builder — bundle services with auto pricing roll-up',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R080'],
    acceptance_criteria: 'Create packages; add/remove services; total auto-calculated; assign to clients',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R082',
    phase: 'Phase 6',
    domain: 'Commercial',
    requirement: 'Engagement pack generation from template + assigned services',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R071', 'R081'],
    acceptance_criteria: 'Pack auto-populated from client assignments; includes scope, T&Cs, AML trigger; status DRAFT',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R083',
    phase: 'Phase 6',
    domain: 'Commercial',
    requirement: 'Digital signature capture — signed doc becomes immutable',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R082'],
    acceptance_criteria: 'Sign → immutable trigger; signed_at/by recorded; onboarding state advances',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R090',
    phase: 'Phase 7',
    domain: 'Workflow',
    requirement: 'Job management — create, assign, track recurring work per client',
    type: 'UI',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'XL' as Requirement['complexity'],
    dependencies: ['R072'],
    acceptance_criteria: 'Jobs table with type, client, assignee, status, recurrence, due dates; kanban view',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Core ClickUp replacement',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R091',
    phase: 'Phase 7',
    domain: 'Workflow',
    requirement: 'Task derivation engine — auto-derive next actions from pending items',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R090'],
    acceptance_criteria: 'System generates tasks from: pending checks, unsigned engagements, overdue jobs, filing deadlines',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R092',
    phase: 'Phase 7',
    domain: 'Workflow',
    requirement: 'Time entries — log time against jobs/tasks',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R090'],
    acceptance_criteria: 'Time entry with job link, duration, date, notes; WIP tracking',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Replaces ClickUp time tracking',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R093',
    phase: 'Phase 7',
    domain: 'Workflow',
    requirement: 'Recurrence engine — auto-create jobs on schedule',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R090'],
    acceptance_criteria: 'Monthly bookkeeping, quarterly VAT, annual accounts — auto-generated from templates',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R094',
    phase: 'Phase 7',
    domain: 'Workflow',
    requirement: 'Onboarding state machine with blocker explanations',
    type: 'Workflow',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R050', 'R060', 'R082'],
    acceptance_criteria: 'S0→S7 deterministic; structured error payloads; UI shows why transition blocked',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R095',
    phase: 'Phase 7',
    domain: 'Workflow',
    requirement: 'Controlled overrides — role-gated with rationale + audit',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R094'],
    acceptance_criteria: 'OWNER/CO can force transition; rationale required; flagged in UI; audited',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R100',
    phase: 'Phase 8',
    domain: 'Integration',
    requirement: 'Companies House API — company profile lookup',
    type: 'Integration',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'Search by name/number; retrieve: officers, filings, SIC codes, registered address',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Already built in CompanyQuery — adapt for platform',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R101',
    phase: 'Phase 8',
    domain: 'Integration',
    requirement: 'Companies House snapshot storage — immutable',
    type: 'Database',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R100'],
    acceptance_criteria: 'companies_house_snapshots table; immutable; links to client; captures filing history',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R102',
    phase: 'Phase 8',
    domain: 'Integration',
    requirement: 'Companies House monitoring — filing deadline alerts',
    type: 'Workflow',
    priority: 'Medium' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R100', 'R017'],
    acceptance_criteria: 'Auto-check confirmation statement and accounts deadlines; alert if overdue',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R103',
    phase: 'Phase 8',
    domain: 'Integration',
    requirement: 'Auto-populate client data from Companies House on creation',
    type: 'Workflow',
    priority: 'Medium' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R100'],
    acceptance_criteria: 'When company number provided, pre-fill: name, address, SIC, officers as contacts',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R110',
    phase: 'Phase 9',
    domain: 'Governance',
    requirement: 'Full audit coverage — every lifecycle action logged',
    type: 'Database',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['All prior'],
    acceptance_criteria: 'Engagement, signature, compliance, risk, state transitions, overrides all produce audit_logs entries',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Test Group A dependency',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R111',
    phase: 'Phase 9',
    domain: 'Governance',
    requirement: 'Central audit viewer — timeline per client',
    type: 'UI',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R110'],
    acceptance_criteria: 'Searchable, filterable audit timeline; actor + role + action + timestamp + metadata',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Regulator-ready',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R112',
    phase: 'Phase 9',
    domain: 'Governance',
    requirement: 'AML evidence bundle export — one-click per client',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R014', 'R015', 'R110'],
    acceptance_criteria: 'Export: all AML checks, documents, risk assessments, audit trail as PDF/ZIP bundle',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'HMRC/AAT may request at any time',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R113',
    phase: 'Phase 9',
    domain: 'Governance',
    requirement: 'Retention policy enforcement — 5yr AML, soft-delete others',
    type: 'Database',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R110'],
    acceptance_criteria: 'AML data protected from deletion for 5 years; non-AML data soft-deletable; legal hold flag',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R120',
    phase: 'Phase 10',
    domain: 'Agent',
    requirement: 'BeaconBot co-pilot — contextual AI assistant',
    type: 'Agent',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'XL' as Requirement['complexity'],
    dependencies: ['R094', 'R110'],
    acceptance_criteria: 'Context-aware; sees client data; suggests actions; drafts documents; firm-scoped',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: 'Claude API integration',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R121',
    phase: 'Phase 10',
    domain: 'Agent',
    requirement: 'Onboarding Agent — auto-creates compliance cases + engagement packs',
    type: 'Agent',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R050', 'R082'],
    acceptance_criteria: 'Monitors new clients; triggers risk assessment; generates engagement; sends welcome',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: 'Highest-impact background agent',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R122',
    phase: 'Phase 10',
    domain: 'Agent',
    requirement: 'Compliance Monitor Agent — watches for expiring checks and deadlines',
    type: 'Agent',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R102', 'R017'],
    acceptance_criteria: 'Daily scan; flags overdue items; alerts staff; updates dashboard',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R123',
    phase: 'Phase 10',
    domain: 'Agent',
    requirement: 'Agent governance — all actions audited, irreversible actions require human approval',
    type: 'Security',
    priority: 'Critical' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R110', 'R120'],
    acceptance_criteria: 'agent_id in audit_logs; DRAFT-only for sends/submissions; human approval gate',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: 'Non-negotiable for regulated platform',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R130',
    phase: 'Phase 11',
    domain: 'Portal',
    requirement: 'Portal auth — CLIENT role with restricted permissions',
    type: 'Security',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'Separate auth flow; CLIENT role in JWT; sees only own data scoped by firm_id + client_id',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R131',
    phase: 'Phase 11',
    domain: 'Portal',
    requirement: 'Document upload — client uploads ID docs for AML',
    type: 'Portal',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R061', 'R130'],
    acceptance_criteria: 'Upload flow; status visible to client; firm staff can verify',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R132',
    phase: 'Phase 11',
    domain: 'Portal',
    requirement: 'Engagement status view + invoice/payment view',
    type: 'Portal',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R083', 'R130'],
    acceptance_criteria: 'Client sees signed engagement, outstanding invoices; pay via Stripe/Xero',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R133',
    phase: 'Phase 11',
    domain: 'Portal',
    requirement: 'Messaging — conversation thread with firm',
    type: 'Portal',
    priority: 'Medium' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R130'],
    acceptance_criteria: 'Messages table; scoped to client + firm; human-reviewed before response',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R140',
    phase: 'Phase 12',
    domain: 'Config',
    requirement: 'Multi-firm provisioning — self-service signup',
    type: 'Workflow',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'Sign up → create firm → seed defaults → usable immediately',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R141',
    phase: 'Phase 12',
    domain: 'Config',
    requirement: 'White-label portal — firm branding on client portal',
    type: 'Config',
    priority: 'Medium' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R130'],
    acceptance_criteria: 'Custom logo, colours, domain; configurable per firm',
    saas_tier_gate: 'Scale+',
    upgrade_feature: false,
    notes: 'Upgrade trigger from Growth',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R142',
    phase: 'Phase 12',
    domain: 'Config',
    requirement: 'Multi-business support — one firm manages multiple entities',
    type: 'Config',
    priority: 'Medium' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R001'],
    acceptance_criteria: 'Firm can have multiple \'businesses\' each with own clients; shared staff',
    saas_tier_gate: 'Growth+',
    upgrade_feature: false,
    notes: 'Upgrade trigger from Starter',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R143',
    phase: 'Phase 12',
    domain: 'Config',
    requirement: 'SaaS billing — tiered plans + per-client pricing',
    type: 'Integration',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R140'],
    acceptance_criteria: 'Stripe integration; plan enforcement; overage billing; usage tracking',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: null,
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R144',
    phase: 'Phase 12',
    domain: 'Config',
    requirement: 'Feature gating — database-level per plan tier',
    type: 'Database',
    priority: 'High' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'M' as Requirement['complexity'],
    dependencies: ['R143'],
    acceptance_criteria: 'firm_plan column; DB functions check plan before allowing gated features',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'Agents, portal, white-label gated by plan',
    source: 'upload' as Requirement['source'],
  },
  {
    ref_id: 'R145',
    phase: 'Phase 12',
    domain: 'Config',
    requirement: 'Platform admin dashboard — system-level management',
    type: 'UI',
    priority: 'Medium' as Requirement['priority'],
    status: 'Backlog' as Requirement['status'],
    assigned_to: 'Claude Code',
    complexity: 'L' as Requirement['complexity'],
    dependencies: ['R140'],
    acceptance_criteria: 'Firm management, plan changes, system health, aggregate metrics',
    saas_tier_gate: 'All Tiers',
    upgrade_feature: false,
    notes: 'PLATFORM_ADMIN role only',
    source: 'upload' as Requirement['source'],
  },
]

export const SEED_PHASES: SeedPhase[] = [
  {
    phase: 'Phase 0',
    description: 'Fix Blockers (Provisioning + Roles)',
    week_target: 'NOW',
    dependencies: null,
    total_reqs: 3,
    critical_count: 3,
    gate_criteria: 'Firm provisioned; JWT correct; no role errors',
  },
  {
    phase: 'Phase 1',
    description: 'Data Model Restructure (Two-Level Compliance)',
    week_target: 'Week 1-2',
    dependencies: 'Phase 0',
    total_reqs: 12,
    critical_count: 8,
    gate_criteria: 'Contacts + risk assessments + AML tables live; RLS passes; immutability holds; templates seeded',
  },
  {
    phase: 'Phase 1.5',
    description: 'Risk Scoring Engine',
    week_target: 'Week 2-3',
    dependencies: 'Phase 1',
    total_reqs: 3,
    critical_count: 2,
    gate_criteria: 'Scoring function immutable; weighted algorithm correct; override governance works',
  },
  {
    phase: 'Phase 2',
    description: 'Core UI Patterns',
    week_target: 'Week 2-4',
    dependencies: 'Phase 1',
    total_reqs: 5,
    critical_count: 0,
    gate_criteria: 'Status bar renders; accordion expands from schema; contact page with tabs',
  },
  {
    phase: 'Phase 3',
    description: 'Risk Assessment Flow',
    week_target: 'Week 3-5',
    dependencies: 'Phases 1, 2',
    total_reqs: 4,
    critical_count: 1,
    gate_criteria: 'Full questionnaire from template; required field enforcement; approve workflow; score calculated',
  },
  {
    phase: 'Phase 4',
    description: 'AML Check Flow',
    week_target: 'Week 4-6',
    dependencies: 'Phases 1, 2',
    total_reqs: 3,
    critical_count: 0,
    gate_criteria: 'Manual AML entry works; documents uploaded; verification levels enforced',
  },
  {
    phase: 'Phase 5',
    description: 'Template Management',
    week_target: 'Week 5-7',
    dependencies: 'Phases 1, 3',
    total_reqs: 4,
    critical_count: 0,
    gate_criteria: 'Firm can clone + customise templates; versioning preserves existing assessments',
  },
  {
    phase: 'Phase 6',
    description: 'Engagement & Commercial',
    week_target: 'Week 6-8',
    dependencies: 'Phase 5',
    total_reqs: 4,
    critical_count: 0,
    gate_criteria: 'Service catalogue CRUD; package builder; engagement pack lifecycle; signature immutable',
  },
  {
    phase: 'Phase 7',
    description: 'Deep Workflow Engine',
    week_target: 'Week 7-10',
    dependencies: 'Phases 5, 6',
    total_reqs: 6,
    critical_count: 2,
    gate_criteria: 'Jobs, tasks, time entries, recurrence all functional; state machine with blockers; overrides audited',
  },
  {
    phase: 'Phase 8',
    description: 'Companies House Integration',
    week_target: 'Week 8-10',
    dependencies: 'Phase 1',
    total_reqs: 4,
    critical_count: 0,
    gate_criteria: 'API lookup works; snapshots stored immutably; monitoring alerts configured',
  },
  {
    phase: 'Phase 9',
    description: 'Governance Hardening',
    week_target: 'Week 9-12',
    dependencies: 'Phases 1-8',
    total_reqs: 4,
    critical_count: 1,
    gate_criteria: 'Full audit coverage; evidence export; retention policy; Test Groups A-F pass',
  },
  {
    phase: 'Phase 10',
    description: 'Agent Framework',
    week_target: 'Week 10-14',
    dependencies: 'Phases 7, 9',
    total_reqs: 4,
    critical_count: 1,
    gate_criteria: 'BeaconBot contextual; onboarding agent runs; all actions audited; human approval gates work',
  },
  {
    phase: 'Phase 11',
    description: 'Client Portal',
    week_target: 'Week 12-16',
    dependencies: 'Phases 6, 9',
    total_reqs: 4,
    critical_count: 0,
    gate_criteria: 'Portal auth separate; document upload; engagement view; messaging; Test Group H passes',
  },
  {
    phase: 'Phase 12',
    description: 'SaaS Commercialisation',
    week_target: 'Week 14-20',
    dependencies: 'All prior',
    total_reqs: 6,
    critical_count: 0,
    gate_criteria: 'Self-service signup; billing works; feature gating; white-label + multi-biz as upgrades',
  },
]

export const SEED_CONTENT_CALENDAR: SeedContentCalendar[] = [
  {
    week: 1,
    publish_date: '2026-04-13',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Compliance Made Simple',
    topic: 'Most small businesses don\'t fail because of bad ideas',
    key_message: 'They fail because they miss a filing deadline, forget a VAT return, or get caught out by HMRC. Compliance isn\'t glamorous — but it\'s the foundation everything else sits on.',
    cta: 'If that sounds familiar, let\'s talk → link in bio',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 1,
    publish_date: '2026-04-15',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Behind the Practice',
    topic: 'I left a Product Manager role at Barclays to start an accounting practice',
    key_message: 'Everyone thought I was mad. But I saw something most accountants miss: the tech gap between what\'s possible and what most practices actually use. B&L was built to close that gap.',
    cta: 'What\'s the biggest tech gap in your business? Drop it below',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 1,
    publish_date: '2026-04-16',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Tax & Deadline Alerts',
    topic: '3 deadlines every UK business owner forgets',
    key_message: 'Script: \'If you run a limited company, there are 3 dates that will cost you money if you miss them. [1] Confirmation statement — every 12 months from incorporation. [2] Corporation tax — 9 months after year end. [3] Annual accounts — also 9 months. Miss any of these and Companies House or HMRC will fine you. Set calendar reminders today.\'',
    cta: 'Save this post. Better yet, let us handle it → beacon-ledger.co.uk',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 1,
    publish_date: '2026-04-17',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Automation & Efficiency',
    topic: 'Your accountant shouldn\'t be chasing you for receipts in 2026',
    key_message: 'If your accountant is still emailing you spreadsheets and asking you to post documents, you\'re paying for a service model from 2010. Cloud accounting + automation means real-time visibility, not end-of-year surprises.',
    cta: 'Want to see what a modern setup looks like? DM me \'SETUP\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 2,
    publish_date: '2026-04-20',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Industry Insight',
    topic: 'HMRC is investing £1.75 billion in digital compliance',
    key_message: 'Making Tax Digital for Income Tax starts April 2026 for self-employed earning over £50k. This isn\'t optional. If you\'re still using spreadsheets, the clock is ticking.',
    cta: 'Not sure if you\'re ready? We\'ll check for free → DM \'MTD\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 2,
    publish_date: '2026-04-22',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Compliance Made Simple',
    topic: 'AML checks aren\'t just for banks',
    key_message: 'Every accountant in the UK is legally required to verify client identity before taking them on. It\'s called Anti-Money Laundering compliance, and the fines for getting it wrong are brutal. At B&L, every client goes through a proper AML process before we touch their books.',
    cta: 'Questions about your AML obligations? Let\'s chat',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 2,
    publish_date: '2026-04-23',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Behind the Practice',
    topic: 'What actually happens when you onboard with B&L',
    key_message: 'Script: \'When you sign up with us, here\'s exactly what happens. Day 1: we verify your identity — AML compliance, non-negotiable. Day 2-3: we connect to your Xero, review your books, flag any issues. Day 7: you get a clear picture of where your finances stand. No mystery. No waiting 3 months for bad news.\'',
    cta: 'Ready to experience it? Link in comments',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 2,
    publish_date: '2026-04-24',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Client Wins',
    topic: 'A new client came to us 4 months behind on bookkeeping',
    key_message: 'Their previous accountant had gone quiet. No monthly updates, no VAT reminders, nothing. We caught them up in 2 weeks and found £3,200 in reclaimable expenses they\'d missed. That\'s not magic — it\'s just doing the basics properly.',
    cta: 'If your accountant\'s gone quiet, that\'s a red flag. Let\'s fix it',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 3,
    publish_date: '2026-04-27',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Automation & Efficiency',
    topic: 'I automated 80% of our client onboarding',
    key_message: 'What used to take 2 hours per client now takes 15 minutes. Identity verification, engagement letters, Xero setup, compliance checks — all triggered automatically. The result? More time advising clients, less time on admin.',
    cta: 'Want to know which tools we use? Comment \'STACK\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 3,
    publish_date: '2026-04-29',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Tax & Deadline Alerts',
    topic: 'VAT return deadline: 7 May 2026',
    key_message: 'If your VAT quarter ended 31 March, your return and payment are due by 7 May. Late filing = £200 penalty. Late payment = interest from day one. Don\'t leave it to the last minute.',
    cta: 'Need help with your VAT return? Get in touch this week',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 3,
    publish_date: '2026-04-30',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Compliance Made Simple',
    topic: 'What is a confirmation statement and why should you care',
    key_message: 'Script: \'If you own a limited company, you have to file a confirmation statement with Companies House every year. It confirms your company details are up to date — directors, shareholders, registered address. Miss it and you\'ll get a £5,000 fine and your company could be struck off. It takes 10 minutes to file. Don\'t let it cost you thousands.\'',
    cta: 'We handle this for all our clients — beacon-ledger.co.uk',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 3,
    publish_date: '2026-05-01',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Behind the Practice',
    topic: 'The tools I wish I\'d known about when I started freelancing',
    key_message: 'Xero for bookkeeping. Dext for receipts. GoCardless for getting paid on time. A good accountant to tie it all together. Most freelancers waste months figuring this out by trial and error. You don\'t have to.',
    cta: 'Starting out and need guidance? DM me \'FREELANCER\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 4,
    publish_date: '2026-05-04',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Compliance Made Simple',
    topic: 'GDPR isn\'t just a website cookie banner',
    key_message: 'If you hold client data — invoices, addresses, bank details — you\'re a data controller. That means ICO registration (£40/year), a privacy policy, and proper data handling procedures. Most small businesses skip this entirely.',
    cta: 'Not sure if you\'re ICO registered? Check at ico.org.uk',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 4,
    publish_date: '2026-05-06',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Client Wins',
    topic: 'A restaurant owner asked us to \'just do the VAT\'',
    key_message: 'We found they were on the wrong VAT scheme, overpaying by £400/quarter. Switched them to flat rate, saved £1,600/year. Sometimes the biggest wins come from the simplest questions.',
    cta: 'When did you last review your VAT scheme? It might be costing you',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 4,
    publish_date: '2026-05-07',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Automation & Efficiency',
    topic: 'Stop sending your accountant photos of receipts',
    key_message: 'Script: \'I know you\'re doing it. Blurry photos of Tesco receipts in WhatsApp. There\'s a better way. Download Dext — you take a photo, it extracts the data, and it goes straight into your accounting software. Your accountant gets clean data, you get time back. Takes 5 minutes to set up.\'',
    cta: 'Want us to set this up for you? It\'s included in our onboarding',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 4,
    publish_date: '2026-05-08',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Industry Insight',
    topic: 'AI won\'t replace your accountant. But it will replace bad ones.',
    key_message: 'The accountants who just file returns and disappear? AI can do that already. The ones who advise, plan, and help you grow? That\'s a human skill. At B&L, we use AI to handle the routine so we can focus on what actually moves your business forward.',
    cta: 'How are you using AI in your business? Genuine question — comment below',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 5,
    publish_date: '2026-05-11',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Tax & Deadline Alerts',
    topic: 'Corporation tax: the date that catches everyone out',
    key_message: 'Your corporation tax is due 9 months and 1 day after your accounting year end. But your CT600 return isn\'t due until 12 months after. Most people think they\'re the same deadline. They\'re not. Miss the payment date and HMRC charges interest from day one.',
    cta: 'Check your next CT deadline today — it might be sooner than you think',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 5,
    publish_date: '2026-05-13',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Behind the Practice',
    topic: 'Why I chose AAT over ACCA first',
    key_message: 'Speed to practice. AAT gets you licensed and earning while you study further. ACCA is the long game. I\'m doing both — AAT licensed now, ACCA in progress. For B&L\'s clients, the quality of service is the same. The letters after your name matter less than the advice you give.',
    cta: 'What matters more to you in an accountant — qualifications or results?',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 5,
    publish_date: '2026-05-14',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Compliance Made Simple',
    topic: 'The one Companies House filing that can shut your business down',
    key_message: 'Script: \'Your annual accounts. If you don\'t file them on time, Companies House can strike off your company. That means your business legally stops existing. Your bank account gets frozen. You can\'t trade. I\'ve seen it happen to companies that were doing well — they just forgot to file. Set a reminder 6 months after your year end. Or let your accountant handle it.\'',
    cta: 'We track every deadline for every client — that\'s the B&L difference',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 5,
    publish_date: '2026-05-15',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Automation & Efficiency',
    topic: 'The 3-app stack every small business needs',
    key_message: '1. Xero — your financial source of truth. 2. Dext — receipt capture that actually works. 3. GoCardless — get paid on time, every time. Total cost: under £50/month. Total time saved: 10+ hours/month. That\'s the ROI most business owners don\'t calculate.',
    cta: 'Using all three already? What would you add? Using none? DM me \'STACK\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 6,
    publish_date: '2026-05-18',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Client Wins',
    topic: 'We helped a contractor save £4,800 in their first year',
    key_message: 'They were running as a sole trader when a limited company would have been more tax efficient. Simple restructure, proper salary/dividend split, and claiming legitimate expenses they didn\'t know about. No aggressive schemes — just doing it right.',
    cta: 'Not sure if your business structure is optimal? That\'s exactly what we review in a discovery call',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 6,
    publish_date: '2026-05-20',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Compliance Made Simple',
    topic: 'Your first employee creates 7 new compliance obligations',
    key_message: 'PAYE registration, workplace pension, employment contracts, RTI submissions, auto-enrolment, employer\'s liability insurance, and right-to-work checks. Most business owners hire first and panic second. Do it the other way round.',
    cta: 'Hiring soon? Let\'s make sure you\'re set up properly first',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 6,
    publish_date: '2026-05-21',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Tax & Deadline Alerts',
    topic: 'Self assessment: why April matters even though the deadline is January',
    key_message: 'Script: \'Everyone knows 31 January is the self assessment deadline. But the smart move is starting in April. Why? Your records are fresh. Your accountant isn\'t buried under 11 million other returns. And if you owe tax, you\'ve got 9 months to plan for it instead of scrambling in December. Early bird doesn\'t just get the worm — it gets a lower stress bill.\'',
    cta: 'Want to get ahead of next year\'s return? Let\'s start now → DM \'EARLY\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 6,
    publish_date: '2026-05-22',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Industry Insight',
    topic: 'The accounting profession is losing 17,000 members a year',
    key_message: 'ICAEW and ACCA both report declining membership. Meanwhile, demand for accounting services is at an all-time high. The firms that survive will be the ones that modernise — automation, advisory focus, client portals. The ones that don\'t will join the 17,000.',
    cta: 'If you\'re an accountant reading this — what\'s your modernisation plan?',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 7,
    publish_date: '2026-05-25',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Behind the Practice',
    topic: 'I spend 2 hours a week on content. Here\'s why.',
    key_message: 'Because the best marketing for an accountant isn\'t ads — it\'s proof of competence. Every post I write teaches something real. Every tip saves someone money or stress. That\'s more convincing than any sales pitch.',
    cta: 'What\'s the best business advice you\'ve received from a LinkedIn post?',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 7,
    publish_date: '2026-05-27',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Automation & Efficiency',
    topic: 'Your bookkeeping should take 30 minutes a month, not 3 hours',
    key_message: 'If you\'re spending more than that, something is wrong. Either your chart of accounts is overcomplicated, your receipt capture is manual, or your bank feeds aren\'t connected. We audit all three in our first week with a new client.',
    cta: 'Spending too long on bookkeeping? That\'s fixable — DM \'AUDIT\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 7,
    publish_date: '2026-05-28',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Client Wins',
    topic: 'How we caught a £2,000 error in a new client\'s books',
    key_message: 'Script: \'New client came on board last month. Within the first review, we spotted duplicate supplier payments totalling £2,000. Their previous accountant never caught it because they weren\'t doing monthly reconciliations. We got the money back in 3 weeks. Monthly reconciliation isn\'t exciting, but it pays for itself.\'',
    cta: 'When was your last proper bank reconciliation? If you hesitated, call us',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 7,
    publish_date: '2026-05-29',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Compliance Made Simple',
    topic: 'CIS: the tax scheme that catches subcontractors every time',
    key_message: 'If you work in construction, CIS deductions should be offset against your tax bill. But I\'ve seen dozens of subcontractors who\'ve never claimed them back. That\'s money you\'ve already earned sitting with HMRC. Check your CIS statements — you might be owed thousands.',
    cta: 'Work in construction? Let\'s check if you\'re owed a CIS refund → DM \'CIS\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 8,
    publish_date: '2026-06-01',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Tax & Deadline Alerts',
    topic: 'The penalty for late payroll submissions just went up',
    key_message: 'HMRC now charges £100 per month per 1-9 employees for late RTI submissions. That\'s £1,200/year just for being late. And it compounds — 10-49 employees? £200/month. Running payroll isn\'t optional if you have staff.',
    cta: 'Need payroll sorted? We do it from £40/month — beacon-ledger.co.uk',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 8,
    publish_date: '2026-06-03',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Industry Insight',
    topic: 'Why I tell other accountants to stop selling \'compliance\'',
    key_message: 'Nobody wakes up excited about filing accounts. But they do wake up worried about cash flow, growth, and whether they\'re paying too much tax. Lead with the problem, not the process. Compliance is the floor, not the ceiling.',
    cta: 'Accountants — what\'s your highest-value service that isn\'t compliance?',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 8,
    publish_date: '2026-06-04',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Behind the Practice',
    topic: 'A day in the life of a modern accountant',
    key_message: 'Script: \'People think accountants sit in dark rooms with calculators. Here\'s my actual Tuesday. 8am: review overnight bank feeds for 3 clients in Xero. 9am: discovery call with a new restaurant owner. 10am: submit a VAT return. 11am: chase a client\'s overdue invoice via automated reminder. Afternoon: advisory session on business restructuring. Not a calculator in sight.\'',
    cta: 'This is what modern accounting looks like — beacon-ledger.co.uk',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 8,
    publish_date: '2026-06-05',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Automation & Efficiency',
    topic: 'I just saved a client 6 hours a week with one Xero setting',
    key_message: 'Bank rules. That\'s it. They had 200+ transactions a month being manually categorised. We set up 15 bank rules and now 90% categorise automatically. The client went from dreading bookkeeping to barely thinking about it.',
    cta: 'How many hours do you spend on manual bookkeeping? Be honest',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 9,
    publish_date: '2026-06-08',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Compliance Made Simple',
    topic: 'The difference between bookkeeping and accounting (and why it matters)',
    key_message: 'Bookkeeping records what happened. Accounting tells you what it means. If your \'accountant\' only does the first part, you\'re paying for a data entry service. You deserve someone who reads the story your numbers are telling.',
    cta: 'Do you know what your gross margin is this quarter? If not, we should talk',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 9,
    publish_date: '2026-06-10',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Client Wins',
    topic: 'A pub owner told us \'I don\'t need management accounts\'',
    key_message: 'Three months later, we showed them they\'d been under-pricing their Sunday roasts by 22%. Their food cost ratio was 38% when industry benchmark is 28-32%. One menu adjustment later, they\'re £800/month better off. That\'s what management accounts do.',
    cta: 'Do you know your real cost ratios? Most hospitality businesses don\'t',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 9,
    publish_date: '2026-06-11',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Tax & Deadline Alerts',
    topic: 'Annual accounts: the 3 things Companies House actually checks',
    key_message: 'Script: \'Filing annual accounts isn\'t just about the numbers. Companies House checks three things that catch people out. [1] Is the accounting reference date correct? [2] Are the accounts in the right format for your company size? [3] Is the registered office address current? Get any of these wrong and your filing gets rejected — and the clock keeps ticking on your deadline.\'',
    cta: 'Don\'t risk a late filing — let us handle it → beacon-ledger.co.uk',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 9,
    publish_date: '2026-06-12',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Behind the Practice',
    topic: 'The hardest part of running an accounting practice isn\'t the accounting',
    key_message: 'It\'s the 47 other things. Client comms, compliance monitoring, proposal writing, chasing payments, filing deadlines, CPD tracking. That\'s why I\'m building a platform to handle all of it. More on that soon.',
    cta: 'What\'s the most time-consuming non-accounting task in your business?',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 10,
    publish_date: '2026-06-15',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Automation & Efficiency',
    topic: 'Every new B&L client gets their Xero health-checked in week one',
    key_message: 'We look at 5 things: bank feed connections, chart of accounts structure, VAT scheme settings, recurring invoice setup, and user permissions. 80% of clients have at least 2 issues. A clean Xero is a fast Xero.',
    cta: 'Want a free Xero health check? DM \'HEALTH\' and we\'ll run one',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 10,
    publish_date: '2026-06-17',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Compliance Made Simple',
    topic: 'You need an engagement letter. Yes, even for your mate\'s company.',
    key_message: 'AAT and ACCA both require it. It protects you AND the client. It defines scope, fees, responsibilities, and what happens if things go wrong. No engagement letter = no professional protection. We send one to every single client, no exceptions.',
    cta: 'Accountants: are all your clients under engagement letters? Honestly?',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 10,
    publish_date: '2026-06-18',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Industry Insight',
    topic: 'Why small businesses are switching accountants in record numbers',
    key_message: 'Script: \'The number one reason? Communication. Not price. Not quality. Communication. If your accountant only calls when they need something, that\'s not a relationship — that\'s a transaction. At B&L, every client gets monthly check-ins, proactive deadline alerts, and a direct line to their accountant. Not a call centre. Not a chatbot. A person who knows your business.\'',
    cta: 'Is your accountant proactive or reactive? That\'s the question → beacon-ledger.co.uk',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 10,
    publish_date: '2026-06-19',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Client Wins',
    topic: 'We onboarded a new client in 48 hours flat',
    key_message: 'Discovery call Monday. AML checks Tuesday morning. Xero connected Tuesday afternoon. First bank reconciliation Wednesday. By Thursday they had a clear picture of their finances for the first time in 6 months. That\'s what a modern onboarding looks like.',
    cta: 'Waiting weeks for your accountant to get started? That\'s not normal anymore',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 11,
    publish_date: '2026-06-22',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Tax & Deadline Alerts',
    topic: 'Dividend vs salary: the split that saves directors thousands',
    key_message: 'If you run a limited company and pay yourself only salary, you\'re probably overpaying tax. The optimal split for most directors in 2025/26: £12,570 salary + dividends above that. But the exact numbers depend on your situation — don\'t copy generic advice.',
    cta: 'Want us to calculate your optimal split? DM \'DIVIDEND\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 11,
    publish_date: '2026-06-24',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Behind the Practice',
    topic: 'I\'m AAT licensed, ACCA studying, and ICO registered',
    key_message: 'Why does this matter to you? AAT licence means I\'m supervised for anti-money laundering. ACCA means I\'m working toward chartered status. ICO registration means your data is handled properly. These aren\'t nice-to-haves — they\'re the minimum. Ask your accountant about theirs.',
    cta: 'What credentials do you look for in an accountant? Drop your must-haves below',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 11,
    publish_date: '2026-06-25',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Automation & Efficiency',
    topic: 'The one automation that changed everything for our practice',
    key_message: 'Script: \'Client onboarding. Used to take 2 hours of admin per new client. Now it\'s 15 minutes. Here\'s the flow: client signs engagement letter digitally, that triggers AML verification, which triggers Xero setup, which triggers a welcome email with their login details. All automatic. I just review and approve. That\'s 1.75 hours back per client. With 10 clients a month, that\'s 17 hours saved.\'',
    cta: 'Want to see how we do it? Book a discovery call → beacon-ledger.co.uk',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 11,
    publish_date: '2026-06-26',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Compliance Made Simple',
    topic: 'MTD for Income Tax: what self-employed earners need to know now',
    key_message: 'From April 2026, if you earn over £50k self-employed, you\'ll need to submit quarterly digital updates to HMRC. Not annual. Quarterly. This means compatible software, digital records, and a process that works every 3 months. Start preparing now, not in March.',
    cta: 'Earning over £50k self-employed? Let\'s get you MTD-ready → DM \'MTD\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 12,
    publish_date: '2026-06-29',
    day: 'Monday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Client Wins',
    topic: 'A consulting firm was paying for software they\'d stopped using 8 months ago',
    key_message: '£180/month on three SaaS tools nobody logged into. We found it during our first expense review. Cancelled all three, saved £2,160/year. This is why regular expense audits matter — subscription creep is real.',
    cta: 'When did you last audit your business subscriptions? Might be worth 10 minutes today',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 12,
    publish_date: '2026-07-01',
    day: 'Wednesday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Industry Insight',
    topic: 'The future of accounting isn\'t about numbers. It\'s about decisions.',
    key_message: 'AI will handle data entry, categorisation, and basic reporting within 2 years. What it won\'t do: sit across from a business owner and say \'here\'s what I\'d do if I were you.\' Advisory is the future. Compliance is table stakes.',
    cta: 'What decision would you make differently with better financial advice?',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 12,
    publish_date: '2026-07-02',
    day: 'Thursday',
    channel: 'LinkedIn Video',
    format: 'Video Script (60-90s)',
    pillar: 'Tax & Deadline Alerts',
    topic: 'R&D tax relief: the credit most small businesses don\'t claim',
    key_message: 'Script: \'If your business develops new products, processes, or software, you might qualify for R&D tax relief. And it\'s not just for tech companies. A restaurant developing a new food preservation method? Qualifies. A construction firm testing new materials? Qualifies. Claims average £20,000-£50,000. Most small businesses don\'t even know it exists. Ask your accountant. If they don\'t know what you\'re talking about, ask us.\'',
    cta: 'Think you might qualify? Free eligibility check → DM \'R&D\'',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
  {
    week: 12,
    publish_date: '2026-07-03',
    day: 'Friday',
    channel: 'LinkedIn Post',
    format: 'Text Post',
    pillar: 'Behind the Practice',
    topic: '12 weeks of content later, here\'s what I\'ve learned',
    key_message: 'Consistency beats perfection. The posts that perform best aren\'t the polished ones — they\'re the honest ones. Real client stories (anonymised), real deadlines, real advice. If you\'re an accountant thinking about creating content: just start. Your knowledge is already valuable.',
    cta: 'What content from an accountant would actually be useful to you? Tell me — I\'ll make it',
    script_draft: null,
    status: 'To Draft' as ContentCalendarItem['status'],
    performance: null,
    notes: null,
    source: 'upload' as ContentCalendarItem['source'],
  },
]
